# Generated by Django 4.2.1 on 2023-12-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassShutdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_shutdown', models.CharField(max_length=255, verbose_name='Вид простоя')),
            ],
            options={
                'verbose_name_plural': 'Виды простоев',
            },
        ),
        migrations.CreateModel(
            name='FactorShutdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_shutdown', models.CharField(max_length=255, verbose_name='Фактор простоя')),
            ],
            options={
                'verbose_name_plural': 'Факторы простоев',
            },
        ),
        migrations.CreateModel(
            name='TypeShutdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_shutdown', models.CharField(max_length=255, verbose_name='Тип простоя')),
                ('flag_dr_and_ts', models.BooleanField(default=False, verbose_name='ЦРиТО')),
                ('class_shutdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shutdown.classshutdown')),
            ],
            options={
                'verbose_name_plural': 'Типы простоев',
            },
        ),
        migrations.CreateModel(
            name='Shutdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField(verbose_name='Начало простоя')),
                ('date_end', models.DateTimeField(verbose_name='Окончание простоя')),
                ('interval', models.DurationField(blank=True, null=True, verbose_name='продолжительность')),
                ('agregate_name', models.CharField(max_length=255, verbose_name='Название агрегата')),
                ('flag_classification', models.BooleanField(default=False, verbose_name='Флаг')),
                ('commentary', models.TextField(blank=True, verbose_name='Примечание')),
                ('href_documentation', models.CharField(blank=True, null=True, verbose_name='Связанные документы')),
                ('class_shutdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shutdown.classshutdown')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.details')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.elements')),
                ('factor_shutdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shutdown.factorshutdown')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.machines')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.nodes')),
                ('type_shutdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shutdown.typeshutdown')),
            ],
        ),
        migrations.AddField(
            model_name='factorshutdown',
            name='type_shutdown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shutdown.typeshutdown'),
        ),
    ]
