# Generated by Django 4.2.1 on 2024-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutdown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutdown',
            name='flag_classification',
            field=models.BooleanField(blank=True, default=False, verbose_name='Флаг'),
        ),
    ]
