# Generated by Django 4.2.1 on 2024-01-19 03:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bypass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bypass', models.CharField(blank=True, null=True, unique=True, verbose_name='Название обхода')),
                ('action_bypass', models.CharField(blank=True, null=True, verbose_name='Действие во время обхода')),
            ],
            options={
                'verbose_name_plural': 'Пути обхода',
            },
        ),
        migrations.CreateModel(
            name='Job_titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, null=True, unique=True, verbose_name='Название должности')),
            ],
            options={
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(unique=True, verbose_name='Название отчёта')),
                ('rep_login', models.CharField(blank=True, null=True, verbose_name='Логин обходчика')),
                ('rep_start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время начала')),
                ('rep_stop_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время конца')),
                ('rep_passed', models.CharField(blank=True, default='0/0', null=True, verbose_name='Пройдено меток')),
                ('rep_remark', models.BooleanField(verbose_name='Наличие замечания')),
                ('rep_explanation', models.CharField(blank=True, null=True, verbose_name='Пояснение к замечанию')),
            ],
            options={
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_system', models.CharField(blank=True, null=True, verbose_name='Название системы')),
                ('descriptions_system', models.TextField(blank=True, null=True, verbose_name='Описание системы')),
                ('nfc_id_system', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Метка системы')),
            ],
            options={
                'verbose_name_plural': 'Системы',
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_warn', models.CharField(blank=True, null=True, verbose_name='Название неисправности')),
            ],
            options={
                'verbose_name_plural': 'Неисправности',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=5, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=7, verbose_name='Пароль')),
                ('nfc_id', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Личная метка')),
                ('bypass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineman.bypass')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineman.job_titles')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
