# Generated by Django 4.2.1 on 2024-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0003_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_action', models.CharField(blank=True, null=True, unique=True, verbose_name='Название действия')),
            ],
            options={
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.DeleteModel(
            name='Systems',
        ),
        migrations.AddField(
            model_name='job_titles',
            name='job_action',
            field=models.ManyToManyField(to='lineman.actions'),
        ),
    ]
