# Generated by Django 4.2.1 on 2024-02-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0004_actions_delete_systems_job_titles_job_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warning',
        ),
        migrations.AlterModelOptions(
            name='job_titles',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='bypass',
        ),
        migrations.AlterField(
            model_name='reports',
            name='rep_passed',
            field=models.CharField(blank=True, default='0/0', null=True, verbose_name='Пройдено комнат'),
        ),
        migrations.DeleteModel(
            name='Bypass',
        ),
    ]
