# Generated by Django 4.2.1 on 2024-02-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0005_delete_warning_alter_job_titles_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(unique=True, verbose_name='Название комнаты')),
                ('room_nfcID', models.CharField(max_length=18, unique=True, verbose_name='Метка команты')),
                ('room_actions', models.ManyToManyField(to='lineman.actions')),
            ],
            options={
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
