# Generated by Django 4.2.1 on 2024-02-26 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0006_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_r', models.CharField()),
                ('remark_r', models.CharField()),
            ],
            options={
                'verbose_name': 'undefined',
            },
        ),
        migrations.RemoveField(
            model_name='reports',
            name='rep_explanation',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='rep_passed',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='rep_remark',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='rep_start_time',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='rep_stop_time',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='room_actions',
        ),
        migrations.AddField(
            model_name='reports',
            name='rep_phone_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время на телефоне'),
        ),
        migrations.AddField(
            model_name='reports',
            name='rep_server_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время на сервере'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_job',
            field=models.ManyToManyField(to='lineman.job_titles'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='rep_name',
            field=models.CharField(unique=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='reports',
            name='rep_rooms',
            field=models.ManyToManyField(to='lineman.roomsreport'),
        ),
    ]
