# Generated by Django 4.2.1 on 2024-02-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0007_roomsreport_remove_reports_rep_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_r', models.CharField()),
                ('remark_r', models.CharField(blank=True)),
            ],
            options={
                'verbose_name': 'undefined',
            },
        ),
        migrations.RemoveField(
            model_name='roomsreport',
            name='job_r',
        ),
        migrations.RemoveField(
            model_name='roomsreport',
            name='remark_r',
        ),
        migrations.AddField(
            model_name='roomsreport',
            name='room_r',
            field=models.CharField(blank=True, verbose_name='Название комнаты'),
        ),
        migrations.AddField(
            model_name='roomsreport',
            name='actions_r',
            field=models.ManyToManyField(to='lineman.actionsroom'),
        ),
    ]
