# Generated by Django 4.2.1 on 2024-02-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0008_actionsroom_remove_roomsreport_job_r_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionsroom',
            options={'verbose_name': 'action room'},
        ),
        migrations.AlterModelOptions(
            name='roomsreport',
            options={'verbose_name': 'room report'},
        ),
        migrations.AlterField(
            model_name='reports',
            name='rep_name',
            field=models.CharField(unique=True, verbose_name='Название обходчика'),
        ),
    ]
