# Generated by Django 4.2.1 on 2024-02-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0009_alter_actionsroom_options_alter_roomsreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='rep_login',
            field=models.CharField(default='', verbose_name='Логин обходчика'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='rep_name',
            field=models.CharField(verbose_name='Название профессии'),
        ),
    ]
