# Generated by Django 4.2.1 on 2024-02-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0010_alter_reports_rep_login_alter_reports_rep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='rep_phone_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время на телефоне'),
        ),
    ]
