# Generated by Django 4.2.1 on 2024-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0011_alter_reports_rep_phone_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='rep_phone_time',
            new_name='rep_start_time',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='rep_server_time',
        ),
        migrations.AddField(
            model_name='reports',
            name='rep_stop_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время на сервере'),
        ),
    ]
