# Generated by Django 4.2.1 on 2024-02-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0012_rename_rep_phone_time_reports_rep_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='rep_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='rep_stop_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время конца'),
        ),
    ]
