# Generated by Django 4.2.1 on 2024-02-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0013_alter_reports_rep_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_job',
            field=models.ManyToManyField(to='lineman.actions'),
        ),
    ]
