# Generated by Django 4.2.1 on 2024-02-29 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0016_alter_rooms_room_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_job',
            new_name='room_action',
        ),
    ]
