# Generated by Django 4.2.1 on 2024-03-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0017_rename_room_job_rooms_room_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='rep_string',
            field=models.CharField(blank=True, null=True, verbose_name='Excel'),
        ),
    ]
