# Generated by Django 4.2.1 on 2024-03-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0018_reports_rep_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_titles',
            name='job_action',
            field=models.ManyToManyField(related_name='job_action', to='lineman.actions'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_action',
            field=models.ManyToManyField(related_name='room_action', to='lineman.actions'),
        ),
    ]
