# Generated by Django 4.2.1 on 2024-03-21 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0019_alter_job_titles_job_action_alter_rooms_room_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Durability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dur_name', models.CharField(unique=True, verbose_name='Состояние метки')),
            ],
            options={
                'verbose_name_plural': 'Состояние меток',
            },
        ),
        migrations.CreateModel(
            name='NFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_code', models.CharField(max_length=18, unique=True, verbose_name='Код метки')),
                ('nfc_dur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineman.durability')),
            ],
            options={
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_nfcID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineman.nfc'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nfc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineman.nfc'),
        ),
    ]
