# Generated by Django 4.2.1 on 2024-03-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0020_durability_nfc_alter_rooms_room_nfcid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfc',
            name='nfc_dur',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='room_nfcID',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nfc_id',
        ),
        migrations.DeleteModel(
            name='Durability',
        ),
        migrations.DeleteModel(
            name='NFC',
        ),
    ]
