# Generated by Django 4.2.1 on 2024-03-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0022_durability_nfc_rooms_room_nfcid_users_nfc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logl', models.CharField(verbose_name='Лог')),
                ('timel', models.CharField(verbose_name='Время')),
            ],
            options={
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.AddField(
            model_name='reports',
            name='rep_logs',
            field=models.ManyToManyField(to='lineman.logs'),
        ),
    ]
