# Generated by Django 4.2.1 on 2024-03-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0023_logs_reports_rep_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bul_name', models.CharField(verbose_name='Название станции')),
                ('bul_jobs', models.ManyToManyField(to='lineman.job_titles')),
                ('bul_nfc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineman.nfc')),
                ('bul_rooms', models.ManyToManyField(to='lineman.rooms')),
            ],
            options={
                'verbose_name_plural': 'Станции',
            },
        ),
    ]
