# Generated by Django 4.2.1 on 2024-03-22 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0024_buildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buil_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Смежная таблица',
            },
        ),
        migrations.CreateModel(
            name='BuildingRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(verbose_name='Название станции')),
                ('builing_rooms', models.ManyToManyField(to='lineman.roomsreport')),
            ],
            options={
                'verbose_name': 'building report',
            },
        ),
        migrations.CreateModel(
            name='ReportsBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(verbose_name='Название профессии')),
                ('rep_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('rep_stop_time', models.DateTimeField(blank=True, null=True, verbose_name='Время конца')),
                ('rep_string', models.CharField(blank=True, null=True, verbose_name='Excel')),
                ('rep_buildings', models.ManyToManyField(to='lineman.buildingrooms')),
                ('rep_logs', models.ManyToManyField(to='lineman.logs')),
            ],
            options={
                'verbose_name_plural': 'Отчёты',
            },
        ),
        migrations.CreateModel(
            name='ReportsRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_name', models.CharField(verbose_name='Название профессии')),
                ('rep_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('rep_stop_time', models.DateTimeField(blank=True, null=True, verbose_name='Время конца')),
                ('rep_string', models.CharField(blank=True, null=True, verbose_name='Excel')),
                ('rep_logs', models.ManyToManyField(to='lineman.logs')),
                ('rep_rooms', models.ManyToManyField(to='lineman.roomsreport')),
            ],
            options={
                'verbose_name_plural': 'Отчёты комнат',
            },
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='bul_jobs',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(unique=True, verbose_name='Название участка'),
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
        migrations.AddField(
            model_name='buil_room',
            name='buil_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineman.buildings'),
        ),
        migrations.AddField(
            model_name='buil_room',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lineman.rooms'),
        ),
    ]
