# Generated by Django 4.2.1 on 2024-03-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0025_buil_room_buildingrooms_reportsbuilding_reportsroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionsroom',
            old_name='job_r',
            new_name='name_r',
        ),
    ]
