# Generated by Django 4.2.1 on 2024-03-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0026_rename_job_r_actionsroom_name_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomsreport',
            name='remarks_r',
            field=models.BooleanField(default=False),
        ),
    ]
