# Generated by Django 4.2.1 on 2024-03-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0027_roomsreport_remarks_r'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsbuilding',
            options={'verbose_name_plural': 'Отчёты зданий'},
        ),
    ]
