# Generated by Django 4.2.1 on 2024-03-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0028_alter_reportsbuilding_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingrooms',
            name='builing_rooms',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='bul_nfc',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='bul_rooms',
        ),
        migrations.RemoveField(
            model_name='reportsbuilding',
            name='rep_buildings',
        ),
        migrations.RemoveField(
            model_name='reportsbuilding',
            name='rep_logs',
        ),
        migrations.AlterModelOptions(
            name='reportsroom',
            options={'verbose_name_plural': 'Отчёты участков'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name_plural': 'Участки'},
        ),
        migrations.DeleteModel(
            name='Buil_Room',
        ),
        migrations.DeleteModel(
            name='BuildingRooms',
        ),
        migrations.DeleteModel(
            name='Buildings',
        ),
        migrations.DeleteModel(
            name='ReportsBuilding',
        ),
    ]
