# Generated by Django 4.2.1 on 2024-03-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineman', '0029_remove_buildingrooms_builing_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsreport',
            name='remarks_r',
        ),
    ]
